# Configuration file for the pipeline client.

# Location of the pipeline server, communication occurs via TCP.
server = "127.0.0.1:12345"

# Command to copy a file to the server for processing.
# The following placeholders are replaced:
# - `{client_path}` is the absolute path of the file on the client, see
#   the `[watching]` section for how files are discovered;
# - `{server_filename}` is the name of the file as expected by the pipeline.
#
# This `copy_to_server` command must result in the file being copied to the
# `incoming_directory` (see the server configuration) with file name
# `{server_filename}`.
copy_to_server = [
    "cp",
    "{client_path}",
    "./server/{server_filename}",
]

# Configure how file to process are discovered.
[watching]
# Path of the directory to watch for new files.
directory = "./client"
# The extension of files to process.
extension = "mrc"
# How long ago the last modification should be (in seconds) for the file to be
# considered ready for processing.
last_modif_secs = 10
# How often the client should look for new files in the watched directory, in
# seconds.
refresh_every_secs = 5
