# Configuration file for the pipeline server.

# Location of the server, communication occurs via TCP.
address = "127.0.0.1:12345"

# The directory where the client is expected to send the files to process.
# The `copy_to_server` command on the client side must copy the file to
# process to that directory with the name `{server_filename}`.
incoming_directory = "./server"

# Processing command to apply to incoming files.
# The following placeholders are replaced:
# - `{server_path}` is the path of the file on the server;
# - `{client_file_stem}` is the file name on the client without its extension;
# - `{hash}` is a unique hash identifying the file. Using it as part of the output
#   filename of your processing command guarantees its uniqueness, so that processing
#   different files does not result in some output being overwritten.
processing = [
    "cp",
    "{server_path}",
    "./server/{client_file_stem}-{hash}.tiff",
]
