name: CI

on:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@1.88
      - run: cargo test

  build:
    runs-on: ${{ matrix.platform.os }}
    permissions:
      contents: write
    needs: [tests]
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: windows-latest
            target: x86_64-pc-windows-gnu
    steps:
      - name: install `musl-tools`
        if: runner.os == 'Linux'
        run: sudo apt install -y musl-tools
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: ${{ matrix.platform.target }}
      - name: build
        shell: bash
        run: |
          cargo build --release --target ${{ matrix.platform.target }}
          binname="pipeline"
          asset_name=$binname-${{ matrix.platform.target }}
          target_folder="target/${{ matrix.platform.target }}/release"
          if [ "${{ matrix.platform.os }}" = "windows-latest" ]; then
            target_name=$binname.exe
            archive_name=$asset_name.zip
            (cd $target_folder && 7z a $archive_name $target_name)
          else
            target_name=$binname
            archive_name=$asset_name.tar.gz
            (cd $target_folder && tar -czf $archive_name $target_name)
          fi
          echo "ASSET=$target_folder/$target_name" >> $GITHUB_ENV
          echo "ASSET_NAME=$asset_name" >> $GITHUB_ENV
          echo "RELEASE_ASSET=$target_folder/$archive_name" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ASSET_NAME }}
          path: ${{ env.ASSET }}
      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ${{ env.RELEASE_ASSET }}
